#
# Create certificate for gitea.local before installing Gitea with helm
#
# Make sure that the gitea namespace is created. Create it manually if it is missing:
#   kubectl create namespace gitea
# It is too risky to add it in a manifest, if the manifest is deleted (kubectl delete -f ..), then the
# whole installation is gone forever.
#
# kubectl -n gitea apply -f gitea-tls-secret-deployment.yaml
#
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-tls
  namespace: gitea
spec:
  secretName: gitea-tls
  dnsNames:
    - gitea.gitea.svc.cluster.local
    - gitea.local
    - gitea
    - registry.gitea.svc.cluster.local
  issuerRef:
    name: k3s-ca-issuer
    kind: ClusterIssuer
