name: Run application tests

on:
  workflow_call:

jobs:
  run_tests:
    name: Run dependency audit and application tests
    runs-on: ubuntu-latest
    steps:
      - name: Allow self-signed certificates for Git
        run: git config --global http.sslVerify false

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node_version: '20'

      - name: Install dependencies
        working-directory: ./demoapp
        run: npm install

      - name: Audit dependencies, fail if there are critical vulnerabilities
        working-directory: ./demoapp
        run: npm audit --audit-level=critical

      - name: Run tests
        working-directory: ./demoapp
        run: npm run test
        env:
          NODE_OPTIONS: --max_old_space_size=4096