apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-tls
  namespace: default
spec:
  secretName: echo-tls
  dnsNames:
    - echo.local
  issuerRef:
    name: k3s-ca-issuer
    kind: ClusterIssuer
